# Generated by Django 5.1.4 on 2024-12-19 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_service", "0001_initial"),
        ("borrowing_service", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="borrowingservice",
            index=models.Index(fields=["user"], name="borrowing_s_user_id_f35209_idx"),
        ),
        migrations.AddIndex(
            model_name="borrowingservice",
            index=models.Index(fields=["book"], name="borrowing_s_book_id_afc829_idx"),
        ),
    ]
