# Generated by Django 5.1.4 on 2024-12-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chat_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
